"""Stable policy constants for paired resting HR/RR summaries."""

RESPIRATORY_BASELINE_MIN_COMPARISON_SESSIONS = 3
RESPIRATORY_MINIMUM_VALID_SAMPLES = 4
RESPIRATORY_MINIMUM_VALID_SECONDS = 120.0
RESPIRATORY_MINIMUM_PAIRED_RUN_SECONDS = 30.0
RESPIRATORY_MINIMUM_CONTEXT_COVERAGE_PCT = 50.0
RESPIRATORY_RECHECK_MINIMUM_VALID_SECONDS = 300.0
RESPIRATORY_HIGH_CONTEXT_COVERAGE_PCT = 80.0
RESPIRATORY_ADULT_CONTEXT_RANGE_BRPM = (12.0, 20.0)
RESPIRATORY_ADULT_RECHECK_RANGE_BRPM = (8.0, 25.0)
