[platformio]
default_envs = release
core_dir = .pio-core

[env]
platform = espressif32@6.12.0
board = zeep_sensorhub1_esp32s3
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D CORE_DEBUG_LEVEL=1
    -D ZEEP_FIRMWARE_VERSION=\"sensorhub1-sph0645-laeq-v1.0.0\"
lib_deps =
    bblanchon/ArduinoJson@7.4.3

[env:release]
build_type = release
